name: torch2.0
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.7=py38ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py38h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.5=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.3.1=py38h06a4308_0
  - ftfy=5.8=py_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py38h06a4308_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py38h06a4308_0
  - joblib=1.4.2=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.10.1.7=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.6.82=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib=3.7.2=py38h06a4308_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpld3=0.5.9=py38h06a4308_0
  - mpmath=1.3.0=py38h06a4308_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - numexpr=2.8.4=py38hc78ab66_1
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openai-clip=1.0.1=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.0.14=h5eee18b_0
  - packaging=24.1=py38h06a4308_0
  - pandas=2.0.3=py38h1128e8f_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.3.0=py38h5eee18b_0
  - platformdirs=3.10.0=py38h06a4308_0
  - ply=3.11=py38_0
  - pooch=1.7.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.0.1=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py38h06a4308_0
  - pyyaml=6.0.1=py38h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - regex=2023.10.3=py38h5eee18b_0
  - safetensors=0.4.2=py38ha89cbab_1
  - scipy=1.10.1=py38hf6e8229_1
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py38h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py38h06a4308_0
  - torchaudio=2.0.2=py38_cu118
  - torchtriton=2.0.0=py38
  - torchvision=0.15.2=py38_cu118
  - tornado=6.4.1=py38h5eee18b_0
  - tqdm=4.66.4=py38h2f386ee_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - absl-py==2.2.2
    - accelerate==0.26.0
    - aiofiles==23.2.1
    - altair==5.4.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.5.2
    - asttokens==2.4.1
    - astunparse==1.6.3
    - attrs==24.2.0
    - backcall==0.2.0
    - bitsandbytes==0.41.0
    - bleach==6.1.0
    - blinker==1.8.2
    - blis==0.7.11
    - braceexpand==0.1.7
    - cachetools==5.5.0
    - catalogue==2.0.10
    - cfgv==3.4.0
    - click==8.1.7
    - cloudpathlib==0.19.0
    - confection==0.1.5
    - contexttimer==0.3.3
    - cymem==2.0.8
    - decorator==5.1.1
    - decord==0.6.0
    - distlib==0.3.8
    - easydict==1.13
    - einops==0.6.1
    - einops-exts==0.0.4
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fairscale==0.4.4
    - faiss-gpu==1.7.2
    - fastapi==0.115.12
    - ffmpy==0.5.0
    - flask==3.0.3
    - flask-log-request-id==0.10.1
    - flatbuffers==25.2.10
    - gast==0.4.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-auth==2.40.1
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - gradio==4.16.0
    - gradio-client==0.8.1
    - grpcio==1.70.0
    - h11==0.14.0
    - h5py==3.11.0
    - httpcore==0.17.3
    - httpx==0.24.0
    - huggingface-hub==0.30.2
    - identify==2.6.1
    - imageio==2.35.1
    - importlib-metadata==8.5.0
    - iopath==0.1.10
    - ipython==8.12.3
    - itsdangerous==2.2.0
    - jedi==0.19.1
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kaggle==1.6.17
    - keras==2.13.1
    - langcodes==3.4.1
    - language-data==1.2.0
    - lazy-loader==0.4
    - libclang==18.1.1
    - llava-torch==1.2.2.post1
    - loguru==0.7.3
    - marisa-trie==1.2.0
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markdown2==2.5.1
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - murmurhash==1.0.10
    - narwhals==1.8.4
    - natsort==8.4.0
    - nltk==3.8.1
    - nodeenv==1.9.1
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - opencv-python-headless==4.5.5.64
    - opendatasets==0.1.22
    - opt-einsum==3.4.0
    - orjson==3.10.15
    - parso==0.8.4
    - peft==0.4.0
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pip==25.0.1
    - pkgutil-resolve-name==1.3.10
    - plotly==5.24.1
    - portalocker==2.10.1
    - pre-commit==3.5.0
    - preshed==3.0.9
    - prettytable==3.11.0
    - prompt-toolkit==3.0.48
    - protobuf==4.25.7
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==17.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pycocoevalcap==1.2
    - pycocotools==2.0.7
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydeck==0.9.1
    - pydub==0.25.1
    - pygments==2.18.0
    - pymupdf==1.24.11
    - python-dotenv==1.0.1
    - python-magic==0.4.27
    - python-multipart==0.0.20
    - python-slugify==8.0.4
    - pywavelets==1.4.1
    - referencing==0.35.1
    - requests==2.27.0
    - requests-oauthlib==2.0.0
    - rich==13.8.1
    - rpds-py==0.20.0
    - rsa==4.9.1
    - ruff==0.11.6
    - sacremoses==0.1.1
    - salesforce-lavis==1.0.2
    - scikit-image==0.21.0
    - scikit-learn==1.2.2
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - sentencepiece==0.1.99
    - setuptools==44.1.1
    - shellingham==1.5.4
    - shortuuid==1.0.13
    - smart-open==7.0.4
    - smmap==5.0.1
    - sniffio==1.3.1
    - spacy==3.7.6
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - stack-data==0.6.3
    - starlette==0.44.0
    - std-logger==0.1.6
    - streamlit==1.38.0
    - svgwrite==1.4.3
    - tenacity==8.5.0
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.2
    - tensorboard-logger==0.1.0
    - tensorboardx==2.6.2.2
    - tensorflow==2.13.1
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.4.0
    - text-unidecode==1.3
    - thinc==8.2.5
    - tifffile==2023.7.10
    - timm==0.6.13
    - tokenizers==0.20.3
    - toml==0.10.2
    - tomlkit==0.12.0
    - traitlets==5.14.3
    - transformers==4.46.3
    - typer==0.12.5
    - typing-extensions==4.5.0
    - urllib3==1.26.20
    - uvicorn==0.33.0
    - virtualenv==20.26.6
    - wasabi==1.1.3
    - watchdog==4.0.2
    - wavedrom==2.0.3.post3
    - weasel==0.4.1
    - webdataset==0.2.100
    - webencodings==0.5.1
    - websockets==11.0.3
    - werkzeug==3.0.6
    - wrapt==1.16.0
    - zipp==3.20.2
prefix: /home/dsh/anaconda3/envs/torch2.0
