dataset: Reuters

encoder_dim:
  - [ 10, 128, 1024, 1024, 64 ]
  - [ 10, 128, 1024, 1024, 64 ]

n_classes: 6
drop_rate: 0.5
batch_size: 1024
momentum: 0.98
temperature: 0.5

blr: 5.0e-4
min_blr: 5.0e-4
weight_decay: 0

output_dir: output/Reuters
seed: 1
